### ISSUE TITLE
Class "Webmozart\Assert\Assert" not found 

### ISSUE THREAD

**Issue by mature-woman** [flow-php/etl-adapter-google-sheet#1]
PHP Fatal error:  Uncaught Error: Class "Webmozart\Assert\Assert" not found in /var/www/google_sheets_synchronization/vendor/flow-php/etl-adapter-google-sheet/src/Flow/ETL/Adapter/GoogleSheet/GoogleSheetExtractor.php:27</br>
#### Stack trace:
#0 /var/www/google_sheets_synchronization/vendor/flow-php/etl-adapter-google-sheet/src/Flow/ETL/DSL/GoogleSheet.php(34): Flow\ETL\Adapter\GoogleSheet\GoogleSheetExtractor->__construct()
    #1 /var/www/google_sheets_synchronization/mirzaev/google_sheets/parser/system/public/synchronization.php(10): Flow\ETL\DSL\GoogleSheet::from()
    #2 {main}
  thrown in /var/www/google_sheets_synchronization/vendor/flow-php/etl-adapter-google-sheet/src/Flow/ETL/Adapter/GoogleSheet/GoogleSheetExtractor.php on line 27

### SOLUTION
`composer require webmozart/assert`

**Comment by mature-woman** [comment]
**should be added as a dependency**

**Comment by norberttech** [comment]
it's actually a bug in the code, there is no need to use assertion library in this adapter, I will get it removed as soon as possible, thanks for reporting!

**Comment by norberttech** [comment]
fixed by https://github.com/flow-php/flow/pull/437
